version: "3.9"
services:
  dev-finder-db:
    image: postgres
    restart: always
    container_name: we-collab-db
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
